definitions:

  Errors:
    type: object
    properties:
      errors:
        type: array
        items:
          $ref: "#/definitions/Error"

  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string

  CalculationResponse:
    type: object
    properties:
      firstOperand:
        type: string
      secondOperand:
        type: string
      operation:
        type: string
      result:
        type: string

responses:

  Error400:
    description: Bad request
    schema:
      $ref: "#/definitions/Errors"

  Error404:
    description: Resource not found
    schema:
      $ref: "#/definitions/Errors"

  Error500:
    description: Internal server error
    schema:
      $ref: "#/definitions/Errors"

